define [
  'views/logo'
  'views/overlay'
  'views/pie'
  'views/stock'
  'views/radar'
  'views/line'
  'views/bar'
  'views/stack'
  'views/tree'
  'views/graph'
  'views/scatterplot'
  'views/sankey'
  'views/waterfall'
], () ->
  console.log 'app loaded'